spring:
  profiles:
    active:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowerBowl?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    username: neo
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 686fb1f96b8d661d28125105626214fa
            client-secret: CzK19EJ6e5alY2NeU6K3JurCOZmONG1L
            redirect-uri: "{baseUrl}/oauth2/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname

          naver:
            client-id: BOnebNDZX6WDaA7BJWiD
            client-secret: WvsHfYH1xt
            redirect-uri: "{baseUrl}/oauth2/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: gaebalyong30@gmail.com
    password: "qjmh rbet jcbh xzvp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: flowerbowl
    stack:
      auto: false
    credentials:
      access-key: AKIAQCEUCRHPVWHE37OQ
      secret-key: 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

secret-key: HfdHzFynv0TnzLtkk9xBpCJc2AzwAtW2qhvVgMrA1kk=

payment:
  store_id: imp75223852